spring:
  application:
     name: game-service
  data:
    mongodb:
      host: mongo-db
      port: 27017
      database: simplecasino-game-service

server:
  port: ${PORT:0}

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka_url:http://discovery-server:8761/eureka/}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

feign:
  hystrix:
    enabled: false
  client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000