version: '3'
services:
  discovery-server:
    build: discovery-server
    ports:
          - "8761:8761"
  wallet-service:
    build: wallet-service
    links:
      - discovery-server
      - mysql
    depends_on:
      - discovery-server
      - mysql
  game-service:
    build: game-service
    links:
      - discovery-server
    depends_on:
      - discovery-server
  gateway-service:
    build: gateway-service
    links:
      - game-service
      - wallet-service
    depends_on:
      - game-service
      - wallet-service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
    ports:
      - 27055:27055
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wallet
      MYSQL_USER: simplecasino
      MYSQL_PASSWORD: simplecasino