version: '3'
services:
  discovery-server:
    image: discovery-server
    ports:
      - "8761:8761"

  wallet-service:
    image: wallet-service
    depends_on:
      - discovery-server
      - db-mysql

  game-service:
      image: game-service
      depends_on:
        - discovery-server
        - mongo-db

  gateway-service:
    image: gateway-service
    ports:
      - "9999:9999"
    depends_on:
      - discovery-server

  db-mysql:
    image: mysql:latest
    container_name: db-mysql
    expose:
      - 3306
    volumes:
      - my-datavolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "wallet"
      MYSQL_USER: "simplecasino"
      MYSQL_PASSWORD: "simplecasino"

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    environment:
      - MONGO_DATA_DIR=/data/db
    expose:
      - 27017

volumes:
  my-datavolume: