spring:
  application:
     name: wallet-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://db-mysql:3306/wallet
    username: simplecasino
    password: simplecasino
    hikari:
      connection-timeout: 20000
      minimum-idle: 50
      maximum-pool-size: 200
      idle-timeout: 600000
      max-lifetime: 1200000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    user: simplecasino
    password: simplecasino

server:
  port: ${PORT:0}

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka_url:http://discovery-server:8761/eureka/}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}