spring:
  application:
    name: gatewayservice

server:
  port: ${PORT:9999}

zuul:
  prefix: /api
  ignored-services: '*'
  routes:
    wallet-service:
      path: /ws/**
      serviceId: wallet-service
    gameservice:
      path: /gs/**
      serviceId: game-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka_url:http://discovery-server:8761/eureka/}

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000