spring:
  application:
    name: gatewayservice

server:
  port: ${PORT:9999}

zuul:
  prefix: /api
  ignored-services: '*'
  routes:
    wallet-service:
      path: /walletservice/**
      serviceId: wallet-service
    gameservice:
      path: /gameservice/**
      serviceId: game-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000